### ISSUE TITLE
InvalidOperationException: The HeaderPropagationValues.Headers property has not been initialized

### ISSUE THREAD

**Issue by dmitry-pavlov** [alefranz/HeaderPropagation#5]
Hi @alefranz , 

I am getting the exception below. Please let me know why. Thanks! 

```
System.InvalidOperationException: The HeaderPropagationValues.Headers property has not been initialized. Register the header propagation middleware by adding 'app.UseHeaderPropagation() in the 'Configure(...)' method.
   at Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

ConfigureServices:

```
services.AddHttpClient<IMyServiceClient, MyServiceClient>((provider, client) =>
{
    var serviceSettings = _settings.ExternalServices.MyClient;

    client.BaseAddress = new Uri(serviceSettings.BaseAddress);

}).AddHeaderPropagation();
```

Configure:

```
app.UseHeaderPropagation();
app.UseAuthentication();
app.UseMvc();
```

**Comment by alefranz** [comment]
Hi Dmitry,
thanks for reporting this.

This exception can happen if the collection of captured headers is not initialized by the middleware.
Given you have `app.UseHeaderPropagation();` this should not happen when you use the `HttpClient` in a controller action.
Or are you using `MyServiceClient` out of a controller (e.g. in a HostedService)?

Thank you,
 Alessio

**Comment by alefranz** [comment]
If that is your case, you can temporarily work around the issue manually initializing the header collections:
https://github.com/alefranz/HeaderPropagation/blob/bd2379bde3d6dc031aee6e9444813ba4471117de/samples/WebApplication/OneOfFBackgroundService.cs#L37-L41

I will look into a proper fix for this scenario.

**Comment by dmitry-pavlov** [comment]
Thanks for proposing the workaround @alefranz - will give it a try. 

Yes, you're right - I use it not only in controllers, but in other injected services I have (like background jobs and so on)

I guess it's should be handled more gracefully. Do you have any plans to update it in newer versions of your package? By the way, what about ASPNETCore v3.0 - is it also an issue there, or it's somehow handled?

**Comment by alefranz** [comment]
Hi Dmitry,

another possible workaround for now would be to have a different HttpClient in background jobs.

I have a possible solution to properly handle this scenario but I will hold on a bit as I would prefer to get it done in the AspNetCore project, so that this library continue to be a simple backport.
See aspnet/aspnetcore#12169 and aspnet/aspnetcore#12170 if you want to follow the work there.

To better evaluate what could be the best solution, would you mind explaining a bit your use case? In particular, are your background jobs consuming requests (e.g. messages from a queue) and you would like to use some metadata from your request to be propagated as headers, similar to the ehaders in your incoming http requests? Or you would just be interested in the ability to use the HttpClient bypassing the HeaderPropagation feature when used in a background job?

Thank you,
 Alessio

**Comment by dmitry-pavlov** [comment]
Thanks for the links! 

The case is - we have Hangfire background services. We schedule on app Startup recurring jobs and passing DI services to them. When job is triggered we need to propagate headers to API requests to 3rd external services.

**Comment by wast** [comment]
Hello from the future. I'm using that workaround as well :) 
The same issue with calling a http endpoint from background jobs.

**Comment by jcg122562** [comment]
Hello - I am trying to understand this thread as I got this error below after deploying my web app in azure app service.  Please provide me more information on how to debug and fix this issue.
Thank you.

===
Error: System.InvalidOperationException: The HeaderPropagationValues.Headers property has not been initialized. Register the header propagation middleware by adding 'app.UseHeaderPropagation()' in the 'Configure(...)' method. Header propagation can only be used within the context of an HTTP request.
   at Microsoft.AspNetCore.HeaderPropagation.HeaderPropagationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at EPayMoTo.SecurityService.GetAuthenticationStateAsync() in C:\Users\jcg12\OneDrive\Documents\GitHub\ePayMoTo\Services\SecurityService.cs:line 98
   at EPayMoTo.ApplicationAuthenticationStateProvider.GetApplicationAuthenticationStateAsync() in C:\Users\jcg12\OneDrive\Documents\GitHub\ePayMoTo\Services\ApplicationAuthenticationStateProvider.cs:line 51
   at EPayMoTo.ApplicationAuthenticationStateProvider.GetAuthenticationStateAsync() in C:\Users\jcg12\OneDrive\Documents\GitHub\ePayMoTo\Services\ApplicationAuthenticationStateProvider.cs:line 29
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by alefranz** [comment]
Hi @jcg122562 , are you consuming the `HttpClient` in a background service? if so, you can use the workaround posted above,

By the way, are you using this nuget? if you are on a recent version of .NET, you should use the Microsoft one. However it would not solve this issue and you would still need the workaround.

**Comment by jcg122562** [comment]
Hi Alessio,
Thank you for your reply.  Appreciate it.
Yes I am on recent .NET.  I will try your suggestions.

However, what I have done to make it work.  I PUBLISHED it using RADZEN tool as originally, I created the application using it.
Then just modifying it using visual studio.

After publishing it to the same app service and azure sql db,  from RADZEN, I did not get the error anymore.  This is without changing my application.
I will check this weekend what is the difference that made it to work.

Thank you again.

Jonathan

**Comment by fmattioli** [comment]
I resolvd it doing it:
I created one Client with HeaderPropagation and one without.

```
public static IServiceCollection AddHttpClients(this IServiceCollection services, string proposalsUrl)
{
    services.AddSingleton<IProposalClientFactory, ProposalClientFactory>();

    services.AddHttpClient<IProposalClient, ProposalClient>("WithHeaderPropagation", b =>
    {
        b.BaseAddress = new Uri(proposalsUrl
            .AppendPathSegment("api")
            .AppendPathSegment("v1"));
    }).AddHeaderPropagation();

    services.AddHttpClient<IProposalClient, ProposalClient>("WithoutHeaderPropagation", b =>
    {
        b.BaseAddress = new Uri(proposalsUrl
            .AppendPathSegment("api")
            .AppendPathSegment("v1"));
    });

    return services;
}
```


After that, I created a Factory:

```
public class ProposalClientFactory(IHttpClientFactory httpClientFactory, IFeijucaAuthClient feijucaAuthClient) : IProposalClientFactory
{
    public IProposalClient Create(bool withHeaderPropagation)
    {
        var clientName = withHeaderPropagation ? "WithHeaderPropagation" : "WithoutHeaderPropagation";
        var httpClient = httpClientFactory.CreateClient(clientName);

        return new ProposalClient(httpClient, feijucaAuthClient);
    }
}
```


Now, I am injecting the Factory and I am deciding when I wanna use Header Propagation or no.

`var proposalClient = proposalClientFactory.Create(withHeaderPropagation: false);`


I don't know if it is the better choice. But works for me.
